#==========================swagger 访问接口==================================
#           http://${ip}:10131/swagger-ui/index.html
#           测试环境
#==========================================================================
netty:
  port: 20002

